PREFIX ?= $(HOME)/.local/bin
RC     ?= $(HOME)/.bashrc
OWNER  ?= noxthedevwindev-greatest
REPO   ?= simpledir
ARCH   ?= $(shell uname -m | sed -e 's/x86_64/x86_64/' -e 's/aarch64/arm64/')
ASSET  ?= sd-linux-$(ARCH)
ASSETS ?= $(ASSET) sd.cpp install.sh

CXXFLAGS ?= -std=c++17 -O2 -static-libstdc++ -static-libgcc

.PHONY: all binaries install uninstall test assets release clean

all: binaries

# the whole program is one source file. `sd` is the build output, never edited.
# `sdcfg` is a symlink to it: the program picks its half from argv[0], and both
# names have to exist next to each other for the repo to be usable in place.
binaries: sd sdcfg

sd: sd.cpp
	$(CXX) $(CXXFLAGS) -o $@ $<
	@echo "built $@ ($$(./sd --version))"

sdcfg: sd
	ln -sfn sd $@

# binaries first, then the rc. the wrapper is generated by the installed
# `sdcfg`, so wiring the rc before this step writes an empty block — which is
# exactly what happened the first time round.
install: binaries
	install -Dm755 sd $(PREFIX)/sd
	ln -sfn sd $(PREFIX)/sdcfg
	@echo "installed $(PREFIX)/sd and $(PREFIX)/sdcfg"
	@# refresh rather than skip: a wrapper from an older version is stale, and
	@# an empty one is broken. anything outside the markers is left alone.
	@$(PREFIX)/sdcfg init > $(RC).sd.tmp
	@if grep -q '>>> simpledir >>>' $(RC); then \
		cp -p $(RC) $(RC).bak.$(shell date +%Y%m%d%H%M%S); \
		sed '/# >>> simpledir >>>/,/# <<< simpledir <<</d' $(RC) > $(RC).sd.new; \
	else \
		cp $(RC) $(RC).sd.new; \
	fi
	@cat $(RC).sd.new > $(RC); \
	printf '\n# >>> simpledir >>>\n' >> $(RC); \
	cat $(RC).sd.tmp >> $(RC); \
	printf '# <<< simpledir <<<\n' >> $(RC); \
	rm -f $(RC).sd.tmp $(RC).sd.new; \
	echo "wired $(RC)"

uninstall:

uninstall:
	rm -f $(PREFIX)/sd $(PREFIX)/sdcfg
	cp -p $(RC) $(RC).bak.$(shell date +%Y%m%d%H%M%S)
	sed -i '/# >>> simpledir >>>/,/# <<< simpledir <<</d' $(RC)
	@echo "removed binaries + rc block (config kept in ~/.simpledir)"

# release assets: the binary for this platform, the source, and the installer
assets: sd
	@mkdir -p dist
	@for f in $(ASSETS); do install -m 755 "$$f" "dist/$$f"; done
	@ls -l dist

release: test assets
	@version=$$(sed -n 's/^#define VERSION "\(.*\)"/\1/p' sd.cpp); \
	echo "releasing v$$version"; \
	test -n "$$version" || { echo "could not read VERSION"; exit 1; }; \
	git tag -a "v$$version" -m "$$version"; \
	git push origin "v$$version"; \
	gh release create "v$$version" --title "v$$version" --generate-notes $(foreach f,$(ASSETS),"dist/$(f)#$(f)")

test:
	bash tests/run.sh

clean:
	rm -f sd sdcfg
	rm -rf dist
