PREFIX ?= $(HOME)/.local/bin
RC     ?= $(HOME)/.bashrc
OWNER  ?= noxthedevwindev-greatest
REPO   ?= simpledir
ARCH   ?= $(shell uname -m | sed -e 's/x86_64/x86_64/' -e 's/aarch64/arm64/')
ASSET  ?= sd-linux-$(ARCH)
ASSETS ?= $(ASSET) sd.cpp install.sh

CXXFLAGS ?= -std=c++17 -O2

# Link everything statically. This is the whole v10 release, and the reason is
# arithmetic rather than taste: the dynamic loader costs ~650us before main() even
# starts, which is more than this program spends doing its actual job. Measured
# over 6 interleaved rounds of 120 runs each, median per jump:
#
#   dynamic, as shipped in 9.0.0        1.44 ms
#   static                             0.83 ms
#   static + section gc                0.76 ms
#
# A resident daemon would have been the obvious way to attack this and is the
# wrong answer: parsing the frecency log costs ~120us, a socket round trip costs
# about the same, and `sd name` never reads the log at all. Static also drops the
# last runtime dependency, so "libstdc++ and curl" becomes just curl.
#
# gc-sections matters because a static binary is 3.2MB of libc and libstdc++ with
# most of it unreferenced; throwing those sections away cuts 800KB and another 70us.
STATIC_FLAGS = -static -ffunction-sections -fdata-sections -Wl,--gc-sections

# Not every toolchain ships a static libc. Fall back rather than fail, and say so
# out loud, because a silently slower build is how you end up benchmarking noise.
DYNAMIC_FLAGS = -static-libstdc++ -static-libgcc

.PHONY: all binaries install uninstall test assets release audit-tags check clean

all: binaries

# the whole program is one source file. `sd` is the build output, never edited.
# `sdcfg` is a symlink to it: the program picks its half from argv[0], and both
# names have to exist next to each other for the repo to be usable in place.
binaries: sd sdcfg

sd: sd.cpp
	@if $(CXX) $(CXXFLAGS) $(STATIC_FLAGS) -o $@ $< 2>/dev/null; then \
		:; \
	else \
		echo "note: this toolchain has no static libc, linking dynamically" >&2; \
		$(CXX) $(CXXFLAGS) $(DYNAMIC_FLAGS) -o $@ $<; \
	fi
	@echo "built $@ ($$(./sd --version))"

sdcfg: sd
	ln -sfn sd $@

# binaries first, then the rc. the wrapper is generated by the installed
# `sdcfg`, so wiring the rc before this step writes an empty block — which is
# exactly what happened the first time round.
install: binaries
	install -Dm755 sd $(PREFIX)/sd
	ln -sfn sd $(PREFIX)/sdcfg
	@echo "installed $(PREFIX)/sd and $(PREFIX)/sdcfg"
	@# refresh rather than skip: a wrapper from an older version is stale, and
	@# an empty one is broken. anything outside the markers is left alone.
	@$(PREFIX)/sdcfg init > $(RC).sd.tmp
	@if grep -q '>>> simpledir >>>' $(RC); then \
		cp -p $(RC) $(RC).bak.$(shell date +%Y%m%d%H%M%S); \
		sed '/# >>> simpledir >>>/,/# <<< simpledir <<</d' $(RC) > $(RC).sd.new; \
	else \
		cp $(RC) $(RC).sd.new; \
	fi
	@cat $(RC).sd.new > $(RC); \
	printf '\n# >>> simpledir >>>\n' >> $(RC); \
	cat $(RC).sd.tmp >> $(RC); \
	printf '# <<< simpledir <<<\n' >> $(RC); \
	rm -f $(RC).sd.tmp $(RC).sd.new; \
	echo "wired $(RC)"

uninstall:

uninstall:
	rm -f $(PREFIX)/sd $(PREFIX)/sdcfg
	cp -p $(RC) $(RC).bak.$(shell date +%Y%m%d%H%M%S)
	sed -i '/# >>> simpledir >>>/,/# <<< simpledir <<</d' $(RC)
	@echo "removed binaries + rc block (config kept in ~/.simpledir)"

# release assets: the binary for this platform under the name the installer
# looks for, plus the source and the installer. dist/ is wiped first — a stale
# file from an older build is exactly how you ship the wrong binary.
assets: sd
	@rm -rf dist
	@mkdir -p dist
	install -m 755 sd "dist/$(ASSET)"
	install -m 755 sd.cpp dist/sd.cpp
	install -m 755 install.sh dist/install.sh
	@ls -l dist
	@./sd --version

release: test audit-tags assets
	@version=$$(sed -n 's/^#define VERSION "\(.*\)"/\1/p' sd.cpp); \
	echo "releasing v$$version"; \
	test -n "$$version" || { echo "could not read VERSION"; exit 1; }; \
	git tag -a "v$$version" -m "$$version"; \
	git push origin "v$$version"; \
	gh release create "v$$version" --title "v$$version" --generate-notes $(foreach f,$(ASSETS),"dist/$(f)#$(f)")

test:
	bash tests/run.sh

# Every tag must point at a commit whose own version string matches the tag. The
# v1.0.0 tag pointed one commit late, at the bump to 2.0.0, so `update --to v1.0.0`
# installed a program that called itself 2.0.0 — for four releases, unnoticed,
# because nothing ever compared the two. Run this before tagging.
audit-tags:
	@fail=0; for t in $$(git tag | sort -V); do \
		c=$$(git rev-list -n1 $$t); \
		v=$$(git show $$c:sd.cpp 2>/dev/null | sed -n 's/^#define VERSION "\(.*\)"/\1/p' | head -1); \
		if [ -z "$$v" ]; then v=$$(git show $$c:sd 2>/dev/null | sed -n 's/^VERSION = "\(.*\)"/\1/p' | head -1); fi; \
		if [ -z "$$v" ]; then v=$$(git show $$c:simpledir 2>/dev/null | sed -n 's/^VERSION = "\(.*\)"/\1/p' | head -1); fi; \
		want=$${t#v}; \
		if [ "$$v" = "$$want" ]; then printf '  %-9s ok\n' "$$t"; \
		else printf '  %-9s MISMATCH: tag says %s, that commit says %s\n' "$$t" "$$want" "$${v:-nothing}"; fail=1; fi; \
	done; \
	if [ $$fail -ne 0 ]; then echo "a tag points at the wrong commit. fix the tag, not the version."; exit 1; fi; \
	echo "every tag matches its commit"

# `--version` shows the release's own line, so it has to exist and say something.
# A version number on its own tells you nothing about what you installed.
check: test audit-tags
	@hook=$$(sed -n 's/^#define TAGLINE "\(.*\)"/\1/p' sd.cpp | head -1); \
	if [ -z "$$hook" ]; then echo "TAGLINE is empty. sd --version would just say a number."; exit 1; fi; \
	case "$$hook" in the\ next\ zoxide) echo "TAGLINE is still the old generic one"; exit 1;; esac; \
	printf '  %-9s %s\n' "$$(sed -n 's/^#define VERSION "\(.*\)"/v\1/p' sd.cpp | head -1)" "$$hook"

clean:
	rm -f sd sdcfg
	rm -rf dist
